export enum WeatherCodeEnum {
  CLEAR_SKY = 0,
  MAINLY_CLEAR = 1,
  PARTLY_CLOUDY = 2,
  OVERCAST = 3,
  FOG = 45,
  RIME_FOG = 48,
  DRIZZLE_LIGHT = 51,
  DRIZZLE_MODERATE = 53,
  DRIZZLE_DENSE = 55,
  FREEZING_DRIZZLE_LIGHT = 56,
  FREEZING_DRIZZLE_DENSE = 57,
  RAIN_SLIGHT = 61,
  RAIN_MODERATE = 63,
  RAIN_HEAVY = 65,
  SNOW_SLIGHT = 71,
  SNOW_MODERATE = 73,
  SNOW_HEAVY = 75,
  SNOW_GRAINS = 77,
  RAIN_SHOWERS_SLIGHT = 80,
  RAIN_SHOWERS_MODERATE = 81,
  RAIN_SHOWERS_VIOLENT = 82,
  SNOW_SHOWERS_SLIGHT = 85,
  SNOW_SHOWERS_HEAVY = 86,
  THUNDERSTORM = 95,
  THUNDERSTORM_WITH_HAIL_SLIGHT = 96,
  THUNDERSTORM_WITH_HAIL_HEAVY = 99
}

export const IconsMap = {
  [WeatherCodeEnum.CLEAR_SKY]: 'sun',
  [WeatherCodeEnum.MAINLY_CLEAR]: 'cloud-sun',
  [WeatherCodeEnum.PARTLY_CLOUDY]: 'cloud-sun',
  [WeatherCodeEnum.OVERCAST]: 'cloud',
  [WeatherCodeEnum.FOG]: 'smog',
  [WeatherCodeEnum.RIME_FOG]: 'smog',
  [WeatherCodeEnum.DRIZZLE_LIGHT]: 'cloud-rain',
  [WeatherCodeEnum.DRIZZLE_MODERATE]: 'cloud-rain',
  [WeatherCodeEnum.DRIZZLE_DENSE]: 'cloud-rain',
  [WeatherCodeEnum.FREEZING_DRIZZLE_LIGHT]: 'cloud-rain',
  [WeatherCodeEnum.FREEZING_DRIZZLE_DENSE]: 'cloud-rain',
  [WeatherCodeEnum.RAIN_SLIGHT]: 'cloud-showers-heavy',
  [WeatherCodeEnum.RAIN_MODERATE]: 'cloud-showers-heavy',
  [WeatherCodeEnum.RAIN_HEAVY]: 'cloud-showers-heavy',
  [WeatherCodeEnum.SNOW_SLIGHT]: 'snowflake',
  [WeatherCodeEnum.SNOW_MODERATE]: 'snowflake',
  [WeatherCodeEnum.SNOW_HEAVY]: 'snowflake',
  [WeatherCodeEnum.SNOW_GRAINS]: 'snowflake',
  [WeatherCodeEnum.RAIN_SHOWERS_SLIGHT]: 'cloud-showers-heavy',
  [WeatherCodeEnum.RAIN_SHOWERS_MODERATE]: 'cloud-showers-heavy',
  [WeatherCodeEnum.RAIN_SHOWERS_VIOLENT]: 'cloud-showers-heavy',
  [WeatherCodeEnum.SNOW_SHOWERS_SLIGHT]: 'snowflake',
  [WeatherCodeEnum.SNOW_SHOWERS_HEAVY]: 'snowflake',
  [WeatherCodeEnum.THUNDERSTORM]: 'bolt',
  [WeatherCodeEnum.THUNDERSTORM_WITH_HAIL_SLIGHT]: 'bolt',
  [WeatherCodeEnum.THUNDERSTORM_WITH_HAIL_HEAVY]: 'bolt'
};
